//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabolatoryApp.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeHasLastTime
    {
        public int Id_Employe { get; set; }
        public System.DateTime LastTime { get; set; }
        public bool isDelete { get; set; }
    
        public virtual Employes Employes { get; set; }
    }
}
