//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabolatoryApp.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id_Service { get; set; }
        public System.DateTime DateOfCreate { get; set; }
        public int StatusService_Id { get; set; }
        public int StatusOrder_Id { get; set; }
        public int AmountDayForCreate { get; set; }
    
        public virtual StatusOrder StatusOrder { get; set; }
        public virtual StatusService StatusService { get; set; }
        public virtual Services Services { get; set; }
    }
}
